### ISSUE TITLE
[Data Pipeline] 본몬 텍스트 전처리

### ISSUE THREAD

**Issue by NDjust** [NDjust/Generate-HeadLine#12]
본문 데이터에 불필요한 데이터들이 좀 많이 들어가 있어서 전처리 과정에 대한 피드백 및 아이디어 부탁드립니다.

1. 사진 첨부 텍스트 
<img width="968" alt="image" src="https://user-images.githubusercontent.com/47904523/74124149-af295580-4c14-11ea-9c5e-9e04106cd042.png">

2. 자바 스크립트 코드 
![image](https://user-images.githubusercontent.com/47904523/74124191-cff1ab00-4c14-11ea-9278-78f49a9165b1.png)
3. 홍보 및 추천 글 
![image](https://user-images.githubusercontent.com/47904523/74124224-ec8de300-4c14-11ea-9675-5f4758cd6652.png)

**Comment by svclaw2000** [comment]
<h4>특정 태그 제거</h4>

- Crawling.py 53-54번째 줄 아래처럼 수정

```
for content in soup.find_all("div", {"class": "par"}):
    [s.extract() for s in content('script')] # 스크립트 관련 1
    [s.extract() for s in content('span')] # 스리립트 관련 2
    [s.extract() for s in content('a', {'target': '_blank'})] # 검작색 삼각형으로 시작하는 광고, 홍보 문구
    """
    [s.extract() for s in content('제거할 태그')]
    위 코드를 실행하면 content에서 해당 태그가 없어짐. pop() 같은 개념
    """
    body += content.text
```

- 제거는 되지만 content의 모든 태그에 대해 for문을 돌리기 때문에 속도가 느려질 것으로 예상
- 우선은 이 방법을 사용하는 것이 최선인 듯
