### ISSUE TITLE
[Data Analysis] 제목, 본문 상관분석 데이터

### ISSUE THREAD

**Issue by NDjust** [NDjust/Generate-HeadLine#14]
데이터 형태

<img width="577" alt="image" src="https://user-images.githubusercontent.com/47904523/74209020-523ba700-4cc9-11ea-8754-e7b25b79a5e3.png">

이전 데이터 전처리 요청하신대로 형태소가 분리된 형태로 만들어서 처리해놨습니다. 

전치리가 완전히 깔끔하게는 안나오는 점 양해 부탁드리고 추가로 전처리 필요하신 부분이나 이상한 부분 있으면 코멘트 남겨주세요. 

+ 추가로 WordNet은 Pre-trained 된 모델을 찾고 있고 데이터 양도 계속 쌓이는대로 학습 시킨 후에 바로 전달해드릴게요.

위 전처리된 데이터와 원본 데이터 두개 모두 성아님께 전달해놓겠습니다.

**Comment by parkseonga** [comment]
![image](https://user-images.githubusercontent.com/33725048/74211127-dabe4580-4cd1-11ea-84e9-de811c220f25.png)


![image](https://user-images.githubusercontent.com/33725048/74211138-e6aa0780-4cd1-11ea-898b-01dbe6e8ac6e.png)
 
숫자가 다음과 같이 다 빠져있던데 일부러 제외시킨건가요?

**Comment by NDjust** [comment]
전처리 추가 요구사항

1. . , '', [] 등 특수문자, 영어 등 제거하지 않고 품사 분류
    - 키워드 상관분석을 위해 키워드 추출은 직접해서 분석하겠습니다.
    - 키워드 및 본문 모두 품사 분류해주세요
        -> 본문에서 추출한 키워드의 품사 기반으로 키워드 나열 순서를 정하기 위함
2. 가능하다면 고유명사(이름) 부분 추가해주세요
    - 유명인사들은 인식하지만 그 외는 무시하는 것 같아요
